export const element2 = [

    {name: "Energy Sector Matters", text: "Ministry of Power formulates the general policy in the Electricity Sector. Electricity is a concurrent subject at Entry 38 in List III of the Seventh Schedule of the Constitution of India,1950. The Ministry of Power is primarily responsible for the development of electrical energy in the country. The Ministry is concerned with perspective planning, policy formulation, processing of projects for investment decision, monitoring of the implementation of power projects, training and manpower development and the administration and enactment of legislation in regard to thermal, hydro power generation, transmission and distribution. The Ministry of Power is responsible for the Administration of the Electricity Act, 2003, the Energy Conservation Act, 2001 and to undertake such amendments to these Acts, as may be necessary from me to me, in conformity with the Government's policy  objectives."},

    {name: "In-Direct Tax Matters", text: "In-direct taxes  in the nature of Central Excise Tax, Custom Tax, Sales Tax and Service Tax are source of revenue for Central and/or State Governments. All these taxes have separate and distinguishable taxation laws which provide for levy and collection of tax in a systematic manner. It is a common phenomenon, that disputes with regard to in-direct taxation manners arise quite often on the ground that either a particular product/item is not taxable or on the ground of excessive taxation / double taxation or an inter-State taxation issue. The GST regime has certainly reduced the disputes with regard to Sale Tax to a large extent, however the disputes with regard to Central Excise Tax, Custom Tax and Service Tax is still a growing concern. The taxation law experts at Legal Minds International assist to resolve the taxation disputes before Custom, Excise and Service Tax Appellate Tribunal(CESTAT) and also before various Competent Authorise and Commissioners under the taxation laws."},

    {name: "Litigation & Arbitration", text: "Legal Minds International has expertise in conducting various litigations in the nature of Civil Suits, Appeals, Criminal Matters, N.I.Act matters, Writs, Writ Appeals, Litigations under Arbitration Law U/s. 9, 11, 34, 37; SLPs, NCLT, NCLAT, National and other Consumer Forums, National Green Tribunal etc. Legal Minds International has got rich experience in conducting Arbitrations involving huge financial stakes before different arbitrators consisting of former Judges of High Court and Supreme Court."},

    { name: "Banking and Finance", text: "The Banking and Finance practice of Legal Minds International covers the full range of international and domestic finance activities with particular emphasis on securitization, due-diligence, derivatives, banking, restructuring & insolvency, asset finance, project finance, insurance and other financial services. Our firm represents clients before various legal forums and conduct matters before DRT, DRAT, Consumer Forums, IRDAI, MACT, Banking Ombudsman etc., apart from handling matters relating to dishonour of cheques under NI Act."},

    {name: "Insolvencyand Bankruptcy Code", text: "The Partners at LMI have rich experience in dealing with cases before NCLT and NCLAT arising out of Insolvency and Bankruptcy Code, 2017."},

    {name: "Real Estate", text: "The Partners at LMI advise their clients in the matter pertaining to Real Estate Sector. Legal Minds International prepares legal documentation for the purchase, leasing, sale, mortgage of real estate properties including commercial, industrial, agricultural and residential properties. The firm also advises clients on the applicable local laws, such as stamp dues and requirements of registration. As an integral part of this area of practice, we also advise on licensing and regulatory approvals required from government and statutory agencies. Legal Minds International also handles litigations under The Right to Fair Compensation and Transparency in Land Acquisition, Rehabilitation and Resettlement Act, 2013 and PMPAct,1962."},

    {name: "Infrastructure Projects, Contract Draing and Negoaon", text: "Legal Minds International has got a skilled team of lawyers for advisory and various litigations pertaining to the Infrastructure Projects. Further, LMI also undertakes Comprehensive Contract Management Support for multi -crore contracts of big Corporates wherein a ‘Beginning to End’ legal support would be provided for the contract. The lawyers in Legal Minds International are experts in drafting various types of Contracts and Contract Negotiation."},

    {name: "Labour, Industrial and Service Law", text: " Labour Laws with regard to unorganised Sector is always a matter of concern for big Industries and Corporates. The multifarious Labour and Industrial Law Compliances, the complexities in labour management, the Contract labour issues etc., are the key areas wherein the Industries and Corporates need legal and specialised support. Legal Minds International specialises in all the Labour and Industrial Legislations in India viz., Industrial Dispute Act 1947, Trade Union Act 1926, Minimum Wages Act 1948, Payment of Wages Act 1936, Factories Act 1948, Payment of Bonus Act 1965, Equal Remuneration Act 1976, Payment of Gratuity Act 1972, Employee’s Compensation Act 1923 etc. LMI advises the industries and Corporates on the above laws and also conducts relevant litigations before various Courts/Tribunals on the subject."},

    {name: "Legal Research and Training:", text: "Legal Minds International is a pioneer law firm in conducting Training Programmes, Symposiums and Workshops on legal subjects relevant to various industries. The training programmes designed by Legal Minds International are mainly meant for Non-Law Executives at all levels, though the executives and assistants in law departments would also be benefited. Legal Minds International has got a dedicated research team who constantly update the Lawyers and Clients in various developments of law on day to day basis."},

]