export const element2 = [

    {name: "Energy Sector Matters", text: "Ministry of Power formulates the general policy in the Electricity Sector. Electricity is a concurrent subject at Entry 38 in List III ofthe Seventh Schedule ofthe Constuon ofIndia,1950. The Ministry of Power is primarily responsible for the development of electrical energy in the country. The Ministry is concerned with perspecve planning, policy formulaon, processing of projects for investment decision, monitoring of the implementaon of power projects, training and manpower development and the administraon and enactment oflegislaon in regard to thermal, hydro power generaon, transmission and distribuon. The Ministry of Power is responsible for the Administraon of the Electricity Act, 2003, the Energy Conservaon Act, 2001 and to undertake such amendments to these Acts, as may be necessary from me to me, in conformity with the Government's policyobjecves."},

    {name: "In-Direct Tax Matters", text: "In-direct taxesin the nature ofCentralExcise Tax, Custom Tax, Sales Tax and Service Tax are source of revenue for Central and/or State Governments. All these taxes have separate and disnguishable taxaon laws which provide forlevyand collecon oftax in a systemac manner. It is a common phenomenon, that disputes with regard to in-direct taxaon maers arise quite oen on the ground that either a parcular product/item is not taxable or on the ground of excessive taxaon / double taxaon or an inter-State taxaon issue. The GSTregime has certainly reduced the disputes with regard to Sale Tax to a large extent, howeverthe disputes with regard to Central Excise Tax, Custom Tax and Service Tax is sll a growing concern. The taxaon law experts at Legal Minds Internaonal assist to resolve the taxaon disputes before Custom, Excise and Service Tax Appellate Tribunal(CESTAT) and also before various Competent Authories and Commissioners underthe taxaon laws. "},

    {name: "Litigation & Arbitration", text: "Legal Minds Internaonal has experse in conducng various ligaons in the nature of Civil Suits,Appeals, Criminal Maers, N.I.Act maers, Writs, Writ Appeals, Ligaons under Arbitraon Law U/s. 9, 11, 34, 37; SLPs, NCLT, NCLAT, Naonal and other Consumer Forums, Naonal Green Tribunal etc. Legal Minds Internaonal has got rich experience in conducng Arbitraons involving huge financial stakes before different arbitrators consisng of former Judges of High Court and Supreme Court."},

    { name: "Banking and Finance", text: "The Banking and Finance pracce of Legal Minds Internaonal covers the full range ofinternaonaland domesc finance acvies with parcular emphasis on securizaon, due-diligence, derivaves, banking, restructuring & insolvency, asset finance, project finance, insurance and other financial services. Our firm represents clients before various legal forums and conduct maers before DRT, DRAT,Consumer Forums, IRDAI, MACT, Banking Ombudsman etc., apart from handling maers relang to dishonorof cheques underNI Act."},

    {name: "Insolvencyand Bankruptcy Code", text: "The Partners at LMI have rich experience in dealing with cases before NCLTand NCLATarising outof Insolvencyand BankruptcyCode, 2017."},

    {name: "Real Estate", text: "The Partners at LMI advise their clients in the maer pertaining to Real Estate Sector. Legal Minds Internaonal prepares legal documentaon for the purchase, leasing, sale, mortgage of real estate properes including commercial, industrial, agricultural and residenal properes. The firm also advises clients on the applicable local laws, such as stamp dues and requirements of registraon. As an integral part of this area of pracce, we also advise on licensing and regulatory approvals required from government and statutory agencies. Legal Minds Internaonal also handles ligaons under The Right to Fair Compensaon and Transparency in Land Acquision, Rehabilitaon and Reselement Act, 2013 and PMPAct,1962"},

    {name: "Infrastructure Projects, Contract Draing and Negoaon", text: "Legal Minds Internaonal has got a skilled team of lawyers for advisory and various ligaons pertaining to the Infrastructure Projects. Further, LMI also undertakes Comprehensive Contract Management Support for mul-crore contracts of big Corporates wherein a ‘Beginning to End’ legal support would be provided forthe contract. The lawyers in Legal Minds Internaonal are experts in draing various types ofContracts and Contract Negoaon. "},

    {name: "Labour, Industrial and Service Law", text: "Labour Laws with regard to unorganised Sector is always a maer of concern for big Industries and Corporates. The mulfarious Labour and Industrial Law Compliances, the complexies in labourmanagement, the Contract labour issues etc., are the key areas wherein the Industries and Corporates need legal and specialised support. Legal Minds Internaonal specialises in all the Labour and Industrial Legislaons in India viz., Industrial Dispute Act 1947, Trade Union Act 1926,Minimum Wages Act 1948, Payment of Wages Act 1936, Factories Act 1948, Payment of Bonus Act 1965, Equal Remuneraon Act 1976, Payment of Gratuity Act 1972, Employee’s Compensaon Act 1923 etc. LMI advises the industries and Corporates on the above laws and also conducts relevant ligaons before various Courts/Tribunals on the subject. ."},

    {name: "Legal Research and Training:", text: "Legal Minds Internaonal is a pioneerlawfirm in conducng Training Programmes, Symposiums and Workshops on legal subjects relevant to various industries. The training programmes designed by Legal Minds Internaonal are mainly meant for Non-Law Execuves at all levels, though the execuves and assistants in lawdepartments would also be benefited. Legal Minds Internaonal has got a dedicated research team who constantly update the Lawyers and Clients in various developments oflawon dayto daybasis."},

]